variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/polymarketbot
  GIT_STRATEGY: clone

stages:
  - build
  - deploy


Build:
  stage: build
  tags:
    - shell
    - rabbit2
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - echo "$SMTH_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$SMTH_REGISTRY_USER" --password-stdin
    - >
      docker build -f Dockerfile --target production
      --build-arg GIT_HASH=${CI_COMMIT_SHORT_SHA}
      --tag ${IMAGE_NAME}:${CI_PIPELINE_IID}
      --label CI_PROJECT_ID=${CI_PROJECT_ID}
      .
    - docker push --quiet ${IMAGE_NAME}:${CI_PIPELINE_IID}
    - docker image prune --all --force --filter="label=CI_PROJECT_ID=${CI_PROJECT_ID}" --filter="until=1h"


Deploy:
  stage: deploy
  needs:
    - job: Build
  tags:
    - shell
    - polybot2
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: prod
  variables:
    REF_FILE_VAR_PROD: $PROD_ENV
  script:
    - cat $REF_FILE_VAR_PROD > .env
    - echo "$SMTH_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$SMTH_REGISTRY_USER" --password-stdin
    - docker pull --quiet ${IMAGE_NAME}:${CI_PIPELINE_IID}
    - docker image tag ${IMAGE_NAME}:${CI_PIPELINE_IID} ${IMAGE_NAME}:${CI_ENVIRONMENT_NAME}
    - docker push --quiet ${IMAGE_NAME}:${CI_ENVIRONMENT_NAME}
    - docker stack deploy -c deploy_prod.yaml --with-registry-auth Prod-polymarketbot
